SEED: 0
ENVS:
  Darwin: /Users/ucaiado/GIT/tennis-rl/Tennis.app
  Linux: /home/aind2/tennis-rl/Reacher_Linux_NoVis/Tennis.x86_64
  Windows: C:/GIT/tennis-rl/Reacher_Windows_x86_64/Tennis.exe
DDPG:
  BATCH_SIZE: 200
  BUFFER_SIZE: 100000
  GAMMA: 0.99
  LR_ACTOR: 0.0001
  LR_CRITIC: 0.001
  TAU: 0.001
  UPDATE_EVERY: 2
  WEIGHT_DECAY: 0.0001
PPO:
  BATCH_SIZE: 62
  DISCOUNT: 0.99
  EPSILON: 0.1
  BETA: 0.01
  SGD_EPOCH: 4
  LR: 0.0001
  TAU: 0.95
  GRADIENT_CLIP: 5
